version: '3.8'

services:
  db:
    image: postgres:15
    container_name: invoice-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: newzen
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: invoicedb
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: