spring:
  application:
    name: demo
  datasource:
    # docker-compose에 설정한 포트(5432)와 DB이름(invoicedb)
    url: jdbc:postgresql://localhost:5432/invoicedb
    # docker-compose에 설정한 아이디
    username: newzen
    # docker-compose에 설정한 비밀번호
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 테이블이 없으면 자동으로 만들어줌
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 실행되는 SQL을 보기 좋게 정렬

  mail:
    host: smtp.gmail.com
    port: 587
    username: zenibooksnewzen@gmail.com  # [변경] 본인 구글 이메일
    password: mabjckymmnixwtal   # [변경] 발급받은 16자리 앱 비밀번호 (띄어쓰기 없이 붙여서 입력 권장)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000