app:
  base-url: http://localhost:8080

spring:
  application:
    name: demo
  datasource:
    # docker-compose에 설정한 포트(5432)와 DB이름(invoicedb)
    url: jdbc:postgresql://localhost:5432/invoicedb
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # 테이블이 없으면 자동으로 만들어줌
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 실행되는 SQL을 보기 좋게 정렬

  profiles:
    include: secret

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.user}  # [변경] 본인 구글 이메일
    password: ${mail.pass}   # [변경] 발급받은 16자리 앱 비밀번호 (띄어쓰기 없이 붙여서 입력 권장)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

---
app:
  base-url: http://20.194.25.99

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN